---
- name: Ensure firewalld is installed
  yum: name=firewalld state=present

- name: Check if Composer is installed.
  stat: path=/usr/local/bin/composer
  register: composer_bin

- name: Confirm firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_status
  ignore_errors: yes


- debug: var=firewalld_status
- debug: var=firewalld_status.rc

- name: Confirm firewalld is enabled
  command: systemctl is-enabled firewalld
  register: firewalld_enabled
  ignore_errors: yes


- debug: var=firewalld_enabled
- debug: var=firewalld_status.rc

  #failed_when: "'not' in firewalld_status.stdout"
  #changed_when: False

#- name: Remove the mask from firewalld to enable firewalld configuration
#  command: systemctl unmask firewalld
#  when: not firewalld_status

- block:
  - name: Ensure Firewalld is running and start at boot
    service: name=firewalld.service state=running enabled=yes
    when: firewalld_status.failed or firewalld_enabled.failed
  rescue:
    - block:
        - command: systemctl unmask firewalld
        - service: name=firewalld.service state=running enabled=yes
        - command: systemctl mask firewalld

- block:
  - name: Allow all access to tcp port 80
    firewalld: service=http permanent=true state=enabled
    notify: restart firewalld
#  rescue:
#    - block:
#        - command: systemctl unmask firewalld
#        - firewalld: service=http permanent=true state=enabled
#          notify: restart firewalld
#        - command: systemctl mask firewalld


- block:
  - name: Allow all access to tcp port 443
    firewalld: service=https permanent=true state=enabled
    notify: restart firewalld
 # rescue:
 #   - block:
 #       - command: systemctl unmask firewalld
 #       - firewalld: service=http permanent=true state=enabled
 #         notify: restart firewalld
 #       - command: systemctl mask firewalld

# - name: Add the mask back to firewalld to keep it protected
#  command: systemctl mask firewalld