---
- name: Ensure firewalld is installed
  yum: name=firewalld state=present

- name: Remove the mask from firewalld to enable firewalld configuration
  command: systemctl unmask firewalld

- block:
  - name: Ensure Firewalld is running and start at boot
    service: name=firewalld.service state=running enabled=yes
  rescue:
    - block:
        - command: systemctl unmask firewalld
        - service: name=firewalld.service state=running enabled=yes
        - command: systemctl mask firewalld

- block:
  - name: Allow all access to tcp port 80
    firewalld: service=http permanent=true state=enabled
    notify: restart firewalld
  rescue:
    - block:
        - command: systemctl unmask firewalld
        - firewalld: service=http permanent=true state=enabled
          notify: restart firewalld
        - command: systemctl mask firewalld


- block:
  - name: Allow all access to tcp port 443
    firewalld: service=https permanent=true state=enabled
    notify: restart firewalld
  rescue:
    - block:
        - command: systemctl unmask firewalld
        - firewalld: service=http permanent=true state=enabled
          notify: restart firewalld
        - command: systemctl mask firewalld

- name: Remove the mask from firewalld to enable restart
  command: systemctl mask firewalld