---
# Installs and enables apache on webservers

- name: Ensure Apache is installed
  yum: name=httpd state=present

- name: Enable mod_macro for easier vhosts configuration
  lineinfile: dest=/etc/httpd/conf.modules.d/00-base.conf state=present line="LoadModule macro_module modules/mod_macro.so"

- name: Ensure Apache is running and start at boot
  service: name=httpd state=running enabled=yes

- name: Disable MPM-prefork
  lineinfile: dest=/etc/httpd/conf.modules.d/00-mpm.conf state=present regexp='^LoadModule mpm_prefork_module.*' line='#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'

- name: Enable MPM-Event
  lineinfile: dest=/etc/httpd/conf.modules.d/00-mpm.conf state=present regexp='^#LoadModule mpm_event_module.*' line='LoadModule mpm_event_module modules/mod_mpm_event.so'

- name: Configure php-fpm instead of mod_php
  lineinfile: dest=/etc/httpd/conf.d/php.conf state=present insertafter='^\s*SetHandler application/x-httpd-php' line='\tSetHandler "proxy:fcgi://127.0.0.1:9000"'

- name: Disable mod_php
  lineinfile: dest=/etc/httpd/conf.d/php.conf state=present regexp='^\s*SetHandler application/x-httpd-php$' line='\t#SetHandler application/x-httpd-php'

- name: "php-fpm: Catch workers output"
  lineinfile: dest=/etc/php-fpm.d/www.conf state=present regexp='^catch_workers_output = .*' line='catch_workers_output = yes'

- name: "php-fpm: redirect php-fpm errors to stderr"
  lineinfile: dest=/etc/php-fpm.d/www.conf state=present regexp='^php_admin_value[error_log] = .*' line='php_admin_value[error_log] = stderr'

- name: Restart php-fpm
  service: name=php-fpm state=restarted

- name: Restart httpd
  service: name=httpd state=restarted
