---
# Installs and enables apache on webservers

- name: Ensure Apache is installed
  yum: name=httpd state=present

- name: Enable mod_macro for easier vhosts configuration
  lineinfile: dest=/etc/httpd/conf.modules.d/00-base.conf state=present line="LoadModule macro_module modules/mod_macro.so"
  notify: restart httpd

- name: Ensure Apache is running and start at boot
  service: name=httpd state=running enabled=yes

- name: Disable MPM-prefork
  lineinfile: dest=/etc/httpd/conf.modules.d/00-mpm.conf state=present regexp='^LoadModule mpm_prefork_module.*' line='#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so' backrefs=yes
  notify: restart httpd

- name: Enable MPM-Event
  lineinfile: dest=/etc/httpd/conf.modules.d/00-mpm.conf state=present regexp='LoadModule mpm_event_module.*' line='LoadModule mpm_event_module modules/mod_mpm_event.so'
  notify: restart httpd
