---
- debug: msg="PHP VErsion webserver install_php {{ php_version }}"
# Installs php on webservers
- name: Ensure PHP Packages are installed
  yum: name={{ item }} state=present enablerepo=remi,remi-php{{ php_version }}
  with_items:
    - php
    - php-mysqlnd
    - php-pear
    - mod_ssl
    - php-gd
    - php-mbstring
    - php-opcache
    - php-fpm
    - php-devel
    - zlib-devel

- name: Ensure php-fpm is running and start at boot
  service: name=php-fpm state=running enabled=yes

