---
- name: Create vhosts.conf if not exist
  template: src=templates/vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf owner=root group=root mode=0644 force=no
  notify: restart httpd

- name: Verify VHosts directories exists
  file: path="/var/www/{{ item.name }}" state=directory mode=0755 owner="{{ site_os_user }}" group=users
  with_items: "{{ apache_vhosts }}"

- name: Verify logs directories exists
  file: path="/var/www/{{ item.name }}/log" state=directory mode=0755 owner="{{ site_os_user }}" group=users
  with_items: "{{ apache_vhosts }}"