---
- name: Create vhosts.conf if not exist
  template: src=templates/vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf owner=root group=root mode=0644 force=no
  notify: restart httpd

- name: Verify VHosts directories exists
  file: path="{{ item.path }}" state=directory mode=0755 owner="{{ site_os_user }}" group="{{ site_os_group }}"
  with_items: "{{ apache_vhosts }}"
  notify: restart httpd

- name: Verify logs directories exists
  file: path="{{ item.path }}/log" state=directory mode=0755 owner="{{ site_os_user }}" group="{{ site_os_group }}"
  with_items: "{{ apache_vhosts }}"
  notify: restart httpd