---
- name: restart httpd
  service: name=httpd state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart webserver
  include: handlers/restart_webserver.yml

- name: restart memcached
  service: name=memcached state=restarted

- name: restart firewalld
  block:
    - command: systemctl unmask firewalld
    - service: name=firewalld state=restarted
    - command: systemctl mask firewalld

#  include: handlers/restart_firewalld.yml
