---
- name: restart firewalld
  include: handlers/restart_firewalld.yml

- name: restart httpd
  service: name=httpd state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart webserver
  include: handlers/restart_webserver.yml

- name: restart memcached
  service: name=memcached state=restarted

- name: restart firewalld service
  service: name=firewalld state=restarted
  notify: mask firewalld

##- name: restart firewalld
##  command: systemctl unmask firewalld
#  notify: restart firewalld service

- name: mask firewalld
  command: systemctl mask firewalld